name: Build and Deploy AMI

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]
jobs:
  name: amibuild test

  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  build_and_deploy_ami:
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: zip application
      run: zip -r webapp.zip
    - name: Packer init
        run: |
          packer init ./packer/ami.pkr.hcl
    - name: Build AMI
      run: |
        packer build ./packer/ami.pkr.hcl
