name: Build and Deploy AMI

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build_and_deploy_ami:
    name: Python 2 Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip application
      run: zip -r webapp.zip .

    - name: Packer init
      run: packer init ./packer/centos-stream.pkr.hcl

    - name: Build AMI
      run: packer build ./packer/centos-stream.pkr.hcl
