name: Build and Deploy AMI

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build_and_deploy_ami:
    name: Python 2 Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip application
      run: zip -r webapp.zip .

    - name: Authenticate up gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        
    - name: Packer init
      run: packer init ./packer/centos-stream.pkr.hcl

    - name: Build AMI
      run: packer build ./packer/centos-stream.pkr.hcl
